language: python

sudo: false

matrix:
  include:
   - env: TOXENV=flake8
     python: 2.7
   - env: TOXENV=isort
     python: 2.7
   - env: TOXENV=py27-1.9
     python: 2.7
   - env: TOXENV=py27-1.10
     python: 2.7
   - env: TOXENV=py34-1.9
     python: 3.4
   - env: TOXENV=py34-1.10
     python: 3.4
   - env: TOXENV=py35-1.9
     python: 3.5
   - env: TOXENV=py35-1.10
     python: 3.5
   - env: TOXENV=py35-master
     python: 3.5

install: pip install tox coveralls

script: tox

after_success: coveralls
